name: Deploy Site

on:
  push:
    branches: [master]

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          lfs: true
          node-version: 22.3.0
      - run: git lfs install
      - run: git lfs pull
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - name: Build site
        run: |
          npm install -g corepack@latest --force
          corepack enable
          pnpm install
          pnpm run build:web

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-page
          folder: web/dist
          single-commit: true
          clean: true
